name: email_service
description: This is the microservice responsible for handling email related tasks.
version: 1.0.0
repository: https://github.com/miauw-social/email-service

environment:
  sdk: ^3.0.5

dependencies:
  dart_amqp: ^0.2.5
  logger: ^1.4.0
  mailer: ^6.0.1
  simple_mustache: ^2.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
